server:
  port: 8084
spring:
  config:
    import: "optional:file:./.local/nihongo-admin.properties,optional:file:../.local/nihongo-admin.properties,optional:file:./.local/audit-secrets-admin.properties,optional:file:./admin/.local/audit-secrets-admin.properties"
  application:
    name: admin-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_SECRET}
